/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberosApp.Vistas;

/**
 *
 * @author lucia
 */
public class RevisarBrigadasView1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form RevisarCuartelesView
     */
    public RevisarBrigadasView1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaSiniestros = new javax.swing.JTable();
        JBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JRBBrigadasNODisponibles = new javax.swing.JRadioButton();
        JRBBrigadasDisponibles = new javax.swing.JRadioButton();
        JBDisponibleOEnLabor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Revisar Brigadas");

        JTablaSiniestros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTablaSiniestros);

        JBSalir.setText("Salir");

        jLabel1.setText("Selecciona una opcion para ver las Brigadas Activas e Inactivas ");

        JRBBrigadasNODisponibles.setText("Brigadas En Labor");
        JRBBrigadasNODisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBBrigadasNODisponiblesActionPerformed(evt);
            }
        });

        JRBBrigadasDisponibles.setText("Brigadas Disponibles");
        JRBBrigadasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBBrigadasDisponiblesActionPerformed(evt);
            }
        });

        JBDisponibleOEnLabor.setText("Cambiar Disponible/En Labor");
        JBDisponibleOEnLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDisponibleOEnLaborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JRBBrigadasNODisponibles)
                            .addComponent(JRBBrigadasDisponibles))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBDisponibleOEnLabor)
                        .addGap(152, 152, 152)
                        .addComponent(JBSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(JRBBrigadasDisponibles)
                .addGap(18, 18, 18)
                .addComponent(JRBBrigadasNODisponibles)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalir)
                    .addComponent(JBDisponibleOEnLabor))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBBrigadasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBBrigadasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBBrigadasDisponiblesActionPerformed

    private void JRBBrigadasNODisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBBrigadasNODisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBBrigadasNODisponiblesActionPerformed

    private void JBDisponibleOEnLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDisponibleOEnLaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBDisponibleOEnLaborActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBDisponibleOEnLabor;
    private javax.swing.JButton JBSalir;
    private javax.swing.JRadioButton JRBBrigadasDisponibles;
    private javax.swing.JRadioButton JRBBrigadasNODisponibles;
    private javax.swing.JTable JTablaSiniestros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
